### ISSUE TITLE
OutOfAfrica_3G09 simulates two haplotypes with very high similarity

### ISSUE THREAD

**Issue by isinaltinkaya** [popsim-consortium/stdpopsim#1311] opened 2022-07-29 08:35 UTC
**Short description of the problem:**

Simulation with OutOfAfrica_3G09 model generates two haplotypes with a very high amount of shared derived sites causing the diploid individuals constructed based on them having a single individual with a very high amount of "mm" sites. 

I am not sure if this is likely to observe this with this demographical model within a small amount of replicate set or if this is a bug.

I observed this in two replicates (replicate 7 and 9) but I will be using replicate 7 as an example.

Homozygosity rate across windows of size 1000000 sites, from position 16000000 to 51000000 of Chromosome 22
![image](https://user-images.githubusercontent.com/33371500/181716103-2ae72e56-384a-479e-9093-65196615904c.png)
![image](https://user-images.githubusercontent.com/33371500/181716254-48601da8-6cc4-48d3-9732-71b1589b750e.png)
![image](https://user-images.githubusercontent.com/33371500/181716349-4f778cf1-7e13-4c36-90be-d75d00b175e2.png)

Number of sites with genotypes MM, Mm, mm across replicates 
![image](https://user-images.githubusercontent.com/33371500/181716919-f9d1cb1a-f0d3-4033-8b32-907373926393.png)
![image](https://user-images.githubusercontent.com/33371500/181716932-9ef1a9dc-28cf-466b-8cd6-c7cae2701b40.png)
![image](https://user-images.githubusercontent.com/33371500/181716948-fa870bf3-b45e-4cd8-ac6d-2dec8a1dfd7a.png)

```
$ bcftools view -H -s tsk_30,tsk_31 rep7test_masked_haplo.vcf |cut -f10-|sort |uniq -c    
 130859 0       0                                                                                                                             
   1647 0       1                                                                                                                             
   1669 1       0                                                                                                                             
  13213 1       1                                                                                                                             
$ bcftools view -H -s tsk_31 rep7test_masked_haplo.vcf |cut -f10-|sort |uniq -c           
 132528 0                                                                                                                                     
  14860 1                                                                                                                                     
$ bcftools view -H -s tsk_30 rep7test_masked_haplo.vcf |cut -f10-|sort |uniq -c           
 132506 0                                                                                                                                     
  14882 1
```

For reference, this is an example for another individual (pop1_ind1 in replicate 7):
tsk_0:
```
132508,0
14880,1
```
tsk_1:
```
132401,0 
14987,1
```
pop1_ind1(hap0+hap1):
```
124165,0|0
8236,0|1
8124,1|0
6863,1|1
```

**How to reproduce the problem:**
model=OutOfAfrica_3G09, contig=Chr22, genetic map=HapMapII_GRCh37, seed= 2563451925
stdpopsim version=0.1.2
python version=Python 3.10.4                                                                                                                                 

Steps:
1- Simulate with the parameters above
2- Mask low recombination sites using the HapMap mask for chr22 (before and after masking does not make a difference in end results)
3- use `ts.write_vcf()` to generate vcf file

Code used in generation of this:
```
###################################################
# FUNCTIONS
#
# read_bed from stdpopsim_dev
def read_bed(mask_fpath, chrom):
        lines = np.loadtxt(
                        mask_fpath,
                        dtype={"names": ("chrom", "left", "right"), "formats": (object, int, int)},
                        delimiter="\t",
                        usecols=(0, 1, 2),
                        )
        in_chrom = lines["chrom"] == f"{chrom}"
        lines = lines.compress(in_chrom)
        intervals = np.array([lines["left"], lines["right"]]).T
        return intervals

# Mask tree by deleting intervals
def mask_tree_sequence(ts, mask_intervals):
        ts = ts.delete_intervals(mask_intervals)
        return ts
###################################################
# define populations
#
ploidy=2

# define population with Nploid individuals
# <pop_id> : <n_individuals_in_pop>
DEF_POPS={
                1 : 50,
                2 : 50,
                3 : 50
                }

#note that msprime>1 and stdpopsim_dev version
#assumes ploidy=2 by default
haplo_list=[]
indv_names=[]

for i, (key, value) in enumerate(DEF_POPS.items()):
        haplo_list.append(value*ploidy)
        for ind in range(value):

                # Using PLINK-like format: <Family-ID>_<Individual-ID>
                # to store <Population-ID>_<Individual-ID>
                indv_names.append(f"pop{key}_ind{str(ind+1)}")
###################################################

species=stdpopsim.get_species("HomSap")
recombination_map_id="HapMapII_GRCh37"
#  rep=7
SEED=2563451925

model=species.get_demographic_model("OutOfAfrica_3G09")
contig = species.get_contig("chr22", genetic_map=recombination_map_id)
samples = model.get_samples(*haplo_list)
engine = stdpopsim.get_engine("msprime")
ts = engine.simulate(model,contig, samples, seed=SEED)

with open("rep7test.tree","w") as tsout:
    ts.dump(tsout)

#  ## Convert tree sequence to VCF file
#  # Using legacy format to avoid multiple instances of sites
with open("rep7test.vcf","w") as vcfout:
        ts.write_vcf(output=vcfout,
                        ploidy=ploidy,
                        contig_id="chr22",
                        position_transform="legacy",
                        individual_names=indv_names)

# Downloaded from https://raw.githubusercontent.com/popsim-consortium/analysis/master/n_t/masks/HapmapII_GRCh37.mask.bed
BED_FILE="HapmapII_GRCh37.mask.bed"

masked_ts=mask_tree_sequence(ts,read_bed(BED_FILE,chrom="chr22"))
with open("rep7test_masked.tree","w") as tsout:
        masked_ts.dump(tsout)

with open("rep7test_masked_haplo.vcf","w") as out:
    masked_ts.write_vcf(out)

with open("rep7test_masked.vcf","w") as vcfout:
        masked_ts.write_vcf(output=vcfout,
                        ploidy=ploidy,
                        contig_id="chr22",
                        position_transform="legacy",
                        individual_names=indv_names)
```

I would appreciate any feedback.
Best regards,
Isin

**Comment by petrelharp** [comment] 2022-08-03 06:00
To make sure I understand - in some reasonable fraction of replicates, you're getting some within-individual runs of homozygosity that are like 20 or 30 Mb long, among 150 individuals? That does seem surprising, but then again chromosome 22 is pretty weird - it has a long section of very low recombination rate, which could easily cause this. However, that's before the 16Mb mark, and you say this is happening after that point.

And, yes, I can confirm, from the vary nice code you've posted - at this seed, we get two hapotypes that have a MRCA only 2.1 years ago from 23Mb to 51Mb. So, now the question is: is this likely? Well, we can extract coalescence probabilities so this is a do-able calculation:
```
import stdpopsim
import numpy as np
import matplotlib.pyplot as plt

species=stdpopsim.get_species("HomSap")
recombination_map_id="HapMapII_GRCh37"
#  rep=7
SEED=2563451925

model=species.get_demographic_model("OutOfAfrica_3G09")
contig = species.get_contig("chr22", genetic_map=recombination_map_id)
samples = model.get_samples(100, 100, 100)
engine = stdpopsim.get_engine("msprime")
ts = engine.simulate(model,contig, samples, seed=SEED)

indivs = [[2*k, 2*k+1] for k in range(int(ts.num_samples / 2))]
x = np.linspace(0, ts.sequence_length, 51)
het = ts.diversity(indivs, windows=x)

fig, ax = plt.subplots()
ax.plot(x[1:] - np.diff(x)/2, het)

low_het = [30, 31]
sts = ts.simplify(low_het)

t = sts.at(50e6)
print(f"Tree from {int(t.interval.left)} to {int(t.interval.right)} has MRCA at {sts.node(t.root).time} years ago,")
gm = contig.recombination_map
genetic_length = gm.physical_to_genetic(t.interval.right) - gm.physical_to_genetic(t.interval.left)
print(f"  a region having genetic length {genetic_length} Morgans")

for n in low_het:
    print(ts.population(ts.node(n).population))

# get coalescence probabilities
dd = model.get_demography_debugger()
tt = np.linspace(0, 30000, 30001)
cr, cp = dd.coalescence_rate_trajectory(tt, {"pop_0": 2})
coal_prob = np.diff(1 - cp)

fig, ax = plt.subplots()
ax.plot(tt[1:] - np.diff(tt)/2, coal_prob)

# probability of coalescing on a segment of at least this genetic length
ibd_prob = np.sum(np.exp(- 2 * tt[1:] * genetic_length) * coal_prob)
print(f"Probability of a segment this long: {ibd_prob}")
```
which tells us that
```
Tree from 23851148 to 51229805 has MRCA at 2.105740425428386 years ago,  a region having genetic length 0.5313007451667885 Morgans
```
and 
```
Probability of a segment this long: 2.1460919710766422e-05
```
That probability is a lot lower than 1/150. But, you did see it in only 1 of 20 replicates. `1/(150 * ibd-prob)` is 310, suggesting you'd get a run of homozygosity this long in 1 of every 310 replicates... so, not terribly likely but also not unreasonable to see it in 1 of 20?

You did see several such long segments - so, I suppose we could look into whether the distribution of these differs from what we expect by chance. This seems pretty difficult. A quick check shows that things are not completely off:
```
>>> dd.mean_coalescence_time({"pop_0":2})
17456.780354768776
>>> ts.diversity(ts.samples(0), mode='branch') / 2
18866.047405674704
```
i.e., the mean coalescence time matches what the model says it should be.

So - I'm thinking that this is surprising but probably expected. If you have ideas of how else to double-check this, they're welcome?

**Comment by lz398** [comment] 2022-08-05 08:20
Thanks for your detailed reply, Peter. I am a postdoc in the same group with Isin, and I guess the issue we encountered is more extreme than what you calculated here:
As far as I understand, we sampled 50 individuals from each of the three populations, and pop1 and pop2 have a larger population size (during recent times), so the coalescent rate will be smaller compared to the result solely based on pop0 here, which will result in a longer waiting time compared with 310. An alternative way of thinking about this is since we only observed such kind of weird individual in pop0 (appeared twice, replicate 7 and 9), we should expect to see such a segment in pop 0 with a much longer waiting time 1/(50* ibd-prob) = 930.
I also suggested Isin simulate more replicates based on the same model to see if she can find similar segments in other populations rather than pop0. Let me know if you think this is reasonable, and I am looking forward to your further advice.
Lei

**Comment by petrelharp** [comment] 2022-08-05 16:24
Ah, good point, that's a factor of 3 difference.

I think the next thing to do would be to see if this happens with the new stdpopsim. I am not aware of anything that has changed that would affect this, but it's the first thing to check. The code will be a little different (but, simpler) because it now inserts individuals.

This is a very tricky thing to tell if it's actually a bug, since it's hard to do the calculations for what should be expected. My calculations above are approximately correct, but does omit some things. My suspicion is still that it is not a bug, just surprising, since the underlying machinery has been tested extensively.

And, the next thing I'd do to check is to run a single-population simulation of fixed size with that genetic map.

**Comment by isinaltinkaya** [comment] 2022-08-10 13:38
Thank you very much for your detailed reply!

I would like to share one more observation in case this could be related:

I thought the chromosome 22 simulation without applying any mask would simulate the whole chromosome (including the low recombination sites), and I observed these sites in output files, too. However, when I look at the positions in genetic map, it does not cover the entire chromosome but it looks like it only covers the high recombination regions. I am not sure if this is intentional though, but I expected it to cover the whole chromosome since the simulation generates data for the whole chromosome:

```
m=stdpopsim.get_species("HomSap").get_genetic_map("HapMapII_GRCh37").get_chromosome_map("chr22").map
np.savetxt("pos2",m.position)
```
```
$ head pos2                                                                             
0.000000000000000000e+00                                                                                                                      
1.605134700000000000e+07
1.605261800000000000e+07
1.605362400000000000e+07
1.605365900000000000e+07
1.605375800000000000e+07
1.605471300000000000e+07
1.605496000000000000e+07
1.605507000000000000e+07
1.605517100000000000e+07
```
Thanks a lot!

Best wishes,
Isin

**Comment by petrelharp** [comment] 2022-08-10 21:23
I'm not sure what you mean? Maybe I'm missing something, but it looks like first position is 0.0, so the map does cover the entire chromosome? Do you mean that the genetic map is constant (and, I think has a low recomb value) on the first 16Mb?

**Comment by isinaltinkaya** [comment] 2022-08-11 06:39
I was just surprised that there are no positions between 0.000000000000000000e+00 and 1.605134700000000000e+07, but maybe I am misunderstanding how the map is being parsed within the program.

**Comment by petrelharp** [comment] 2022-08-11 08:00
The positions provided are the [points at which the recombination rate changes](https://tskit.dev/msprime/docs/stable/rate_maps.html). So, that means that the recombination rate does not change for the first 16Mb (and, if you look at the first entry in the `rate` vector, I think you'll find it's a very low rate). This is a big reason that chr22 can be pretty werid.

**Comment by nspope** [comment] 2024-12-20 23:20
I'm going to close this, feel free to reopen if there's still an issue.

**Closed by nspope** 2024-12-20 23:20 UTC
