### ISSUE TITLE
ImportError: cannot import name XX from partially initialized module 'stdpopsim.qc' (most likely due to a circular import)

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1284] opened 2022-05-31 17:05 UTC
**Short description of the problem:**
I am trying to create a new species in `stdpopsim/qc`, following the instruction in https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#demographic-model-review-process

**How to reproduce the problem:**

```
cd stdpopsim/qc
touch PanTro.py
echo "from . import PanTro" >> __init__.py
cd ../../
pip install .
stdpopsim -h
```

**Suggested fixes:**
No idea

**Comment by petrelharp** [comment] 2022-06-01 03:48
Wow, what the heck. I can confirm this, and tried a bunch of different things (called it `PanTrog.py` instead; added things to the file instead of an empty file; moved a different species last...) and nothing helps. I also have no idea. Ping @andrewkern? @grahamgower?

**Comment by grahamgower** [comment] 2022-06-01 05:48
This problem is introduced only when doing `pip install .`. I guess there is then some confusion about the installed module and the module in the current directory. So, I recommend avoiding that. If you want to run the command line interface use `python -m stdpopsim -h`, which will pull in the stdpopsim module found in the current working directory. And if I really can't persuade you not to install the package, you can do `pip install -e .` to install in editable mode, which allows one to make changes to files (e.g. change git branches) and such changes will be reflected in the "installed" version (it's just a symlink rather than a full install).

**Comment by petrelharp** [comment] 2022-06-01 06:10
Hm - the problem does also occur when doing `python setup.py install --user` (nearly the same thing?). And, it occurs when running `stdpopsim -h` from a different directory (e.g., `/tmp`), so it's not due to confusion with the current working directory. 

However, doing `pip install -e .` *does* work for me. What the heck?

**Comment by petrelharp** [comment] 2022-06-01 07:56
Yep! Once the file is `git add`'ed, it works!

**Comment by petrelharp** [comment] 2022-06-07 16:13
I'll close this, let us know if you have further problems?

**Closed as completed by petrelharp** 2022-06-07 16:13 UTC

**Comment by xin-huang** [comment] 2022-06-07 18:42
it works, I don't have problems now
