### ISSUE TITLE
TreeSequence sequence length is not equal to chromosome length

### ISSUE THREAD

**Issue by isinaltinkaya** [popsim-consortium/stdpopsim#1236] opened 2022-05-04 19:07 UTC
Hi,

I get different numbers when I use tskit to load the TreeSequence and check the sequence length of the chromosome I used in simulations, and when I use stdpopsim to check it
This is human chr 22,
```
ts.sequence_length
51229805
species.genome.get_chromosome(wildcards.contig).length
51304566
```

I am a bit confused, I see that the value below is the same as you report in the manual. What is the difference between these?

**Comment by mufernando** [comment] 2022-05-04 19:33
Can you share how you got the tree sequence above?

**Comment by grahamgower** [comment] 2022-05-05 06:03
Maybe this is due to a mismatch between the recombination map and the chromosome length, as described in #701?

**Comment by mufernando** [comment] 2022-05-05 18:11
yeah, that is what I was thinking also! 

@isinaltinkaya can you check the recombination map length of the Contig?

**Comment by isinaltinkaya** [comment] 2022-05-08 11:57
With human chr22, and genetic map `recombination_map_id="HapMapII_GRCh37"`

```
                model=species.get_demographic_model(wildcards.model_id)
                contig = species.get_contig(wildcards.contig, genetic_map=recombination_map_id)
                samples = model.get_samples(*samples_per_pop)
                engine = stdpopsim.get_engine("msprime")
                ts = engine.simulate(model,contig, samples, seed=SEED[int(wildcards.rep)])     
                                            
                print(contig.recombination_map.get_size())                                         
>45330
                           
                print(contig.recombination_map.get_sequence_length())              
>51229805.0
                                           
                print(contig.recombination_map.get_length())                   
>51229805.0
                                               
                print(ts.sequence_length)                                                                                     
>51229805.0

                print(species.genome.get_chromosome(wildcards.contig).length)                 
>51304566

```

**Comment by isinaltinkaya** [comment] 2022-05-10 07:37
Currently I am using the length defined in `contig.recombination_map.get_length()` to define the amount of invariable sites. I am not sure if this would matter (using 51229805.0 vs 51304566) since it will be the same number for every simulation using the same contig and recombination map. What do you think?

**Comment by grahamgower** [comment] 2022-05-10 09:31
Duplicate of #701.

**Closed by grahamgower** 2022-05-10 09:31 UTC
