### ISSUE TITLE
parameter priors in demographic models

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#503] opened 2020-04-29 16:16 UTC
Any thoughts on adding a new feature that defines demographic models with priors instead of parameter estimates? This would help with reproducing studies that priors for simulations.

**Comment by jeromekelleher** [comment] 2020-04-30 08:12
I can imagine defining a distribution for each of the parameters in the models, which we then sample from when running simulations. Would this do it?

**Comment by grahamgower** [comment] 2020-04-30 09:54
I think this is a duplicate of #299.

**Comment by jeromekelleher** [comment] 2020-04-30 10:00
Agreed.

**Closed by jeromekelleher** 2020-04-30 10:00 UTC
Labels: enhancement
