### ISSUE TITLE
Deprecated pandas operation (`Calling int on a single element Series`)

### ISSUE THREAD

**Issue by daikitag** [popsim-consortium/stdpopsim#1544] opened 2024-02-13 13:36 UTC
**Short description of the problem:**
Importing stdpopsim raises some errors.

**How to reproduce the problem:**
When I import stdpopsim, the following warning message comes out:

`C:\Users\daiki\anaconda3\envs\tstrait\Lib\site-packages\stdpopsim\catalog\HomSap\demographic_models.py:158: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  time=int(extended_GF.time.head(1) - 1), rate=0`

`C:\Users\daiki\anaconda3\envs\tstrait\Lib\site-packages\stdpopsim\catalog\HomSap\demographic_models.py:161: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  time=int(extended_GF.time.tail(1) + 1), rate=0`

**Suggested fixes:**
It might be better to modify the pandas codes that are suggested in the warning message to remove this message.

**Comment by petrelharp** [comment] 2024-02-14 03:49
Thanks for the report; we should indeed update that.

**Comment by petrelharp** [comment] 2024-07-02 16:41
Duplicate of #1493, closing this one.

**Closed by petrelharp** 2024-07-02 16:41 UTC
